### ISSUE TITLE
Add more info into README

### ISSUE THREAD

**Issue by MahmoudMabrok** [Mostafayehya/VehiclesAPI#1]
here 
https://github.com/Mostafayehya/VehiclesAPI/blob/master/vehicles-api/README.md
it needs info about each route 

what is **baseUrl**,
 with `GET` what is response object

**Comment by Mostafayehya** [comment]
Accessing Swagger UI link would give you a full description of the API, and even you can test it, but It is still a work in progress, and you need to run the three services to get the functionality up and running.

**Comment by Mostafayehya** [comment]
You can now get the project up and running
